spring:
  application:
    name: Hansabal

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/hansabal?rewriteBatchedStatements=true}
    username: ${MYSQL_USERNAME:testuser}
    password: ${MYSQL_PASSWORD:testpass}

  jpa:
    hibernate:
      ddl-auto: update
    #    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_ID}
            client-secret: ${OAUTH2_GOOGLE_SECRET}
            scope:
              - email
              - profile
  #  sql:
  #    init:
  #      mode: always                    # 항상 SQL 초기화 실행
  #      data-locations: classpath:data.sql # 생략해도 기본값이지만 명시적으로 작성

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  batch:
    job:
      enabled: false

jwt:
  secret: ${SPRING_JWT_SECRET}
  access-token-expiration: 900000        # 15분 (밀리초)
  refresh-token-expiration: 21600000     # 6시간 (밀리초)

naver:
  client-id: "oZzdyk_N0TEa6HyXjfwg"
  client-secret: "j_3pQgBaa0"