global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m
  external_labels:
    monitor: 'hansabal-monitor'
  query_log_file: query_log_file.log

rule_files:
  - "rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['hansabal_prometheus:9090']
        labels:
          service: 'hansabal-prometheus'

  - job_name: 'node'
    static_configs:
      - targets: ['hansabal_node_exporter:9100']
        labels:
          service: 'hansabal-node'