# gradle build된 JAR 다운로드 + docker build + push + ssh deploy
name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download JAR from S3
        run: |
          mkdir -p build/libs
          aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/artifacts/app-latest.jar build/libs/app.jar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build and Push Docker Image
        run: |
          docker build -f infra/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/hansabal-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/hansabal-backend:latest

      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            # Docker & Compose 설치 (최초 1회)
            if ! command -v docker &> /dev/null; then
              echo "🛠 Installing Docker..."
              curl -fsSL https://get.docker.com | sh
              sudo apt-get update
              sudo apt-get install -y docker-compose-plugin
            fi

            # 프로젝트 디렉토리로 이동
            DEPLOY_DIR="/home/${{ secrets.AWS_EC2_USER }}/hansabal_backend"
            if [ ! -d "$DEPLOY_DIR" ]; then
              git clone https://github.com/${{ github.repository }} "$DEPLOY_DIR"
            fi

            cd "$DEPLOY_DIR" || exit 1
            git pull origin main

            # 환경 변수 파일 세팅
            echo "${{ secrets.ENV }}" > .env
            cp .env ./infra/.env

            # Docker Compose 재시작
            sudo docker compose -f infra/docker-compose.yml pull
            sudo docker compose -f infra/docker-compose.yml down
            sudo docker compose -f infra/docker-compose.yml up -d
