# gradle test + build + upload jar to S3
name: Continuous Integration

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      #      - name: Run tests with Gradle
      #        run: ./gradlew test --stacktrace --info
      #        env:
      #          TESTCONTAINERS_RYUK_DISABLED: true

      - name: Build JAR with Gradle
        run: ./gradlew bootJar --stacktrace --info

      - name: Rename and Upload JAR to S3
        run: |
          JAR_NAME=$(ls build/libs/*.jar | grep -v plain | head -n 1)
          mv "$JAR_NAME" build/libs/hansabal.jar
          aws s3 cp build/libs/hansabal.jar s3://${{ secrets.S3_BUCKET_NAME }}/artifacts/hansabal.jar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
